root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/main ./cmd/server"
bin = "./tmp/main"
full_bin = ""
include_ext = ["go", "tpl", "tmpl", "html", "sql", "yml", "yaml", "toml", "env"]
exclude_dir = ["assets", "tmp", "vendor", "bin", "docs"]
include_dir = []
exclude_file = []
exclude_regex = ["_test\\.go"]
exclude_unchanged = false
follow_symlink = false
log = "build-errors.log"
delay = 1000
stop_on_error = true
send_interrupt = false
kill_delay = "0s"

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"
app = ""

[log]
time = false

[misc]
clean_on_exit = true

[screen]
clear_on_rebuild = true
